### PR TITLE
copy the notebooks

### PR DESCRIPTION
**Pull request by Marie59**
I modify some lines to be able to copy the notebooks and access them in the jupyterlab (keeping the same tree structure).

### CODE REVIEW

**Comment by ctroupin** [comment]
Hello @Marie59, unfortunately not yet time to do it properly but I'll check soon.

**Comment by Alexander-Barth** [comment]
The original idea to have the notebook in /data (not writable by the user), was that the user has to copy the modified files in his home directory and become "responsible" from them. We can easily update the notebook in /data without interfering with the users' data in his home directory.

When the notebooks are already in his home directory (and writable), the user will typically directory work on them.

What would be your envision workflow on updating the containers and still keeping the users' data? Would the user need to keep track of which files from workshop notebooks were modified and backup those?

**Comment by ctroupin** [comment]
thanks Alex, that's an aspect I had forgotten; it obviously makes sense to ensure users don't lose data or their edited Jupyter notebooks every time there is an update.

In `FAIR-EASE` we haven't (yet) thought about how the users would work, and who will be the users, but probably the approach set for `BlueCloud` is relevant.

**Comment by Marie59** [comment]
I am not quite sure I understand so sorry if my answer does not answer anything... ;) So, here in either case the user will need to save/export in his galaxy history his notebooks because every time jupyter interactive tool stops running it will erase all modifications. 
I don't know what is the approach in `BlueCloud` but I was thinking that if it can't match with a galaxy approach we can create a variable `ARG` (like I suggested here https://github.com/gher-uliege/DIVAnd-jupyterhub/pull/5). That way we can have 2 docker images with different tags.

**Comment by ctroupin** [comment]
Hello Marie, 
not sure I understand 100% now but we will manage it.

So in BlueCloud we say we need 1. A directory where users can't write, this is where the notebooks will be downloaded. 2. Another directory where users copy the original notebooks to, then modify them. 

In FAIR-EASE I guess we have to do the same (so users' changes are not copied over when we update).

Concerning the solution you propose and the use of #5: can you help with what is this command
`jupyter trust /work/DIVAnd-Workshop/notebooks/*/*.ipynb`
doing? 
Aren't the notebooks copied to the user's home directory?

**Comment by Marie59** [comment]
I think it allows the contents of the notebooks to be executed without user confirmation. Yes the notebooks are copied maybe the line is indeed missing a `$NB_USER`. I'll fix that

**Comment by Marie59** [comment]
Hi @ctroupin and @Alexander-Barth , 
So, how do we proceed from there ? Do you have still some questions (I am not sure if everything is clear but the main idea is I think)

**Comment by ctroupin** [comment]
Hello @Marie59,
I think it is okay now, let's merge!

**Pull request merged**
