### PR TITLE
Feat : add file and change dockerfile

### PR DESCRIPTION
**Pull request by Marie59**
The last modifications I made during my tests of the galaxy tool (should be good from now on).
@Alexander-Barth and @ctroupin does this seems good to you ?

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
I am wondering if we we can minimize galaxy specific code?
Can you set the environment files using this option?

https://docs.docker.com/engine/reference/commandline/run/#env

**Comment by Marie59** [comment]
> I am wondering if we we can minimize galaxy specific code? Can you set the environment files using these options instead?
> 
> https://docs.docker.com/engine/reference/commandline/run/#env

The issue is that when I launch the tool I don't have access to the options of docker run it's galaxy which does all the work (if I understood correctly what you asked). Maybe we can keep the "galaxy docker image" on a separate branch of this repo not in the master and create a specific galaxy tag for the dockerhub. That way you could keep a simpler image for the not galaxy related work. Would it be possible or is it too difficult ?

**Comment by Alexander-Barth** [comment]
> The issue is that when I launch the tool I don't have access to the options of docker run it's galaxy which does all the work (if I understood correctly what you asked).

Yes, that was the idea of my questions. I like that when all setting related to software "A" remains on the side of software "A" and do not spill over to software "B". It is easier for maintenance and to update software "A" and "B" in the long run. And also for you, I would guess it is easier to have a more direct control of the environment variables that are needed for galaxy.

But I understand that this is not possible. 

Can we the centralize the changes to the run_galaxy.sh ? (see my commend of the proposed changes)

**Comment by Marie59** [comment]
Hi @Alexander-Barth,
So, I tried to centralize the galaxy variables by writing the following in the run_galaxy.sh : 
`export DEBUG=false
export GALAXY_WEB_PORT=10000
export NOTEBOOK_PASSWORD=none
export CORS_ORIGIN=none
export DOCKER_PORT=none
export API_KEY=none
export HISTORY_ID=none
export REMOTE_HOST=none
export GALAXY_URL=none
`
And from what I understand the galaxy configuration allowing to open a jupyterlab is not working with the variables written that way. I did multiple tests and nothing is working. I may not be doing it right or the galaxy configuration just doesn't allow it to work like that. Do you have an idea ?

**Comment by Marie59** [comment]
Great thanks ! Yes I did but I will test again everything now to be sure I did not forget something in all the changes we made.
Ah I don't see your comment about something weird concerning USER. 
Of course I will do it on the new branch. Thanks again !

**Comment by Alexander-Barth** [comment]
Perfect! I am just pushing the docker image:

  abarth/divand-jupyterhub:galaxy-2023-04-25T0904

**Comment by ctroupin** [comment]
Let's close this issue as we're happy with the current solution :partying_face:

**Pull request closed without merging**
